# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os

from PyQt5 import QtCore, QtWidgets, QtGui


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("VectorVision")
        MainWindow.resize(707, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainContainer = QtWidgets.QWidget(self.centralwidget)
        self.mainContainer.setObjectName("mainContainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainContainer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.folderContainer = QtWidgets.QVBoxLayout()
        self.folderContainer.setObjectName("folderContainer")
        self.folderView = QtWidgets.QTreeWidget(self.mainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folderView.sizePolicy().hasHeightForWidth())
        self.folderView.setSizePolicy(sizePolicy)
        self.folderView.setMaximumSize(QtCore.QSize(250, 16777215))
        self.folderView.setObjectName("folderView")
        self.folderView.setHeaderLabels(["Folders"])
        self.folderContainer.addWidget(self.folderView)
        self.uploadFolder = QtWidgets.QPushButton(self.mainContainer)
        self.uploadFolder.setObjectName("uploadFolder")
        self.folderContainer.addWidget(self.uploadFolder)
        self.horizontalLayout.addLayout(self.folderContainer)
        self.viewContainer = QtWidgets.QVBoxLayout()
        self.viewContainer.setObjectName("viewContainer")
        self.imageContainer = QtWidgets.QVBoxLayout()
        self.imageContainer.setObjectName("imageContainer")
        self.viewImage = QtWidgets.QLabel(self.mainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        self.viewImage.setSizePolicy(sizePolicy)
        self.viewImage.setScaledContents(False)
        self.viewImage.setBackgroundRole(QtGui.QPalette.Base)
        self.viewImage.setObjectName("viewImage")
        self.imageContainer.addWidget(self.viewImage)
        self.thumbnailView = QtWidgets.QListWidget(self.mainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumbnailView.sizePolicy().hasHeightForWidth())
        self.thumbnailView.setSizePolicy(sizePolicy)
        self.thumbnailView.setMaximumSize(QtCore.QSize(16777215, 80))
        self.thumbnailView.setFlow(QtWidgets.QListWidget.Flow.LeftToRight)
        self.thumbnailView.setIconSize(QtCore.QSize(100, 100))
        self.thumbnailView.setObjectName("thumbnailView")
        self.imageContainer.addWidget(self.thumbnailView)
        self.viewContainer.addLayout(self.imageContainer)
        self.navigationContainer = QtWidgets.QHBoxLayout()
        self.navigationContainer.setObjectName("navigationContainer")
        self.previousButton = QtWidgets.QPushButton(self.mainContainer)
        self.previousButton.setObjectName("previousButton")
        self.navigationContainer.addWidget(self.previousButton)
        self.rotateButton = QtWidgets.QPushButton(self.mainContainer)
        self.rotateButton.setObjectName("rotateButton")
        self.navigationContainer.addWidget(self.rotateButton)
        self.nextButton = QtWidgets.QPushButton(self.mainContainer)
        self.nextButton.setObjectName("nextButton")
        self.navigationContainer.addWidget(self.nextButton)
        self.viewContainer.addLayout(self.navigationContainer)
        self.messageContainer = QtWidgets.QHBoxLayout()
        self.messageContainer.setObjectName("messageContainer")
        self.promptText = QtWidgets.QPlainTextEdit(self.mainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.promptText.sizePolicy().hasHeightForWidth())
        self.promptText.setSizePolicy(sizePolicy)
        self.promptText.setMinimumSize(QtCore.QSize(0, 0))
        self.promptText.setMaximumSize(QtCore.QSize(16777215, 50))
        self.promptText.setObjectName("promptText")
        self.messageContainer.addWidget(self.promptText)
        self.buttonContainer = QtWidgets.QVBoxLayout()
        self.buttonContainer.setObjectName("buttonContainer")
        self.imageUpload = QtWidgets.QPushButton(self.mainContainer)
        self.imageUpload.setObjectName("imageUpload")
        self.buttonContainer.addWidget(self.imageUpload)
        self.sendMessage = QtWidgets.QPushButton(self.mainContainer)
        self.sendMessage.setObjectName("sendMessage")
        self.buttonContainer.addWidget(self.sendMessage)
        self.messageContainer.addLayout(self.buttonContainer)
        self.viewContainer.addLayout(self.messageContainer)
        self.horizontalLayout.addLayout(self.viewContainer)
        self.verticalLayout.addWidget(self.mainContainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.imageUpload.clicked.connect(self.promptText.clear) # type: ignore
        self.uploadFolder.clicked.connect(self.folderView.update) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("VectorVision", "VectorVision"))
        self.uploadFolder.setText(_translate("VectorVision", "Upload Folder"))
        self.previousButton.setText(_translate("VectorVision", "<"))
        self.rotateButton.setText(_translate("VectorVision", "↻"))
        self.nextButton.setText(_translate("VectorVision", ">"))
        self.imageUpload.setText(_translate("VectorVision", "Upload Image"))
        self.sendMessage.setText(_translate("VectorVision", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
